boardgame_project_finished:
  outputs:
    dev:
      account: yg54986.eu-west-3.aws
      database: BOARDGAME
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: transform
      schema: dbt_fbalseiro
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: DBT_CAPSTONE_PROJECT_WH
    ci:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: dbt_ci
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
  target: dev
